import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientProviders } from "@/components/ClientProviders";
import Link from "next/link";
import { ThemeToggle } from "@/components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProviders>
          {/* NavBar */}
          <nav className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800 px-4 py-2 flex items-center">
            <span className="text-gray-900 dark:text-white font-bold text-lg">
              Code Snippet Maker
            </span>
            <div className="container mx-auto px-6 py-4 flex justify-between items-center">
              <div className="flex gap-6 items-center text-sm font-medium">
                <Link href="/" className="hover:underline">
                  Home
                </Link>
                <Link href="/create" className="hover:underline">
                  Create Snippet
                </Link>
                <Link href="/snippets" className="hover:underline">
                  All Snippets
                </Link>
              </div>
              <ThemeToggle />
            </div>
          </nav>

          {/* Page Content */}
          <main className="container mx-auto px-6 py-8">{children}</main>
        </ClientProviders>
      </body>
    </html>
  );
}

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx,js,jsx}",
    "./components/**/*.{ts,tsx,js,jsx}",
    "./lib/**/*.{ts,tsx,js,jsx}",
  ],
  // ...existing theme and plugins...
}
